spring:
  # redis 基础配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    #    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 5000
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
  mail:
    host: smtp.sina.com
    port: 25
    protocol: smtp
    username: fleetsoft@sina.com
    password: 9a052dc39292b0ab
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.sina.com
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 100MB #限制文件上传大小为100M
# 文件
file:
  file-path: D:/files/
  big-file-path: D:/files/big/
  # 存储图片资源的目录
  img-path: D:/files/img/
  template-path: D:/files/template/
  zip-path: D:/files/zip/
