spring:
  application:
    name: provider-blog
  profiles:
    active: dev
server:
  port: 8083
dubbo:
  application:
    name: provider-article
  scan:
    base-packages:
      - com.fleet.provider.blog.service.impl
  registry:
    protocol: zookeeper
    address: localhost:2181
    client: curator
  protocol:
    name: dubbo
    port: 20881
  provider:
    filter: -exception
