spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 开发
    url: jdbc:mysql://localhost:3306/blog-sys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
mybatis:
  mapper-locations: mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
